"""create crumbs table

Revision ID: 39ad0c116ba2
Revises:
Create Date: 2017-03-28 02:32:27.110802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ad0c116ba2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('crumbs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.Column('date_created', sa.DateTime(), nullable=False),
                    sa.Column('date_modified', sa.DateTime(), nullable=False),
                    sa.Column('status',
                              sa.Enum('active',
                                      'ended',
                                      name='crumb_statuses'),
                              nullable=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crumbs')
    # ### end Alembic commands ###
